### ISSUE TITLE
spelling mistake on main page

### ISSUE THREAD

**Issue by ghost** [flowergardn/tonetags#2]
"tone tags
welcome to the tone tag dictionary!

tone tags are indicators used within speech to help readers understand tone.
they're often used by people with neurodiversity, and they tend to help out a lot.
below are some tone tags, but be aware it's not an `exaustive` list.

this site was made by [astrid](https://astrid.sh/) and is open source on [github](https://github.com/astridlol/tonetags) <3"

_i put the spelling mistake in code format
it should be spelled_ `exhaustive` _! am only providing this correction because my autism wants to think im helpioing and also i do use this source / link it on my carrds and appreciate it as a resource a lot !!_

**Comment by flowergardn** [comment]
Thanks for letting me know! This issue is now fixed 🩷
